# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'covid_detection.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1049, 706)
        Form.setStyleSheet("background-color: rgb(244, 248, 255);r")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 1011, 681))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setIconSize(QtCore.QSize(35, 16))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 151, 121))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.uploadataset = QtWidgets.QPushButton(self.groupBox)
        self.uploadataset.setGeometry(QtCore.QRect(20, 40, 101, 61))
        self.uploadataset.setMinimumSize(QtCore.QSize(101, 0))
        self.uploadataset.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.uploadataset.setStyleSheet("\n"
"background: transparent;")
        self.uploadataset.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/upload (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uploadataset.setIcon(icon)
        self.uploadataset.setIconSize(QtCore.QSize(50, 50))
        self.uploadataset.setAutoRepeatDelay(300)
        self.uploadataset.setObjectName("uploadataset")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(170, 10, 791, 121))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 40, 181, 61))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(190, 20, 501, 31))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(190, 80, 501, 31))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 140, 951, 491))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 471, 401))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.listWidget = QtWidgets.QListWidget(self.groupBox_4)
        self.listWidget.setGeometry(QtCore.QRect(10, 50, 141, 311))
        self.listWidget.setStyleSheet("background: transparent;")
        self.listWidget.setObjectName("listWidget")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 161, 21))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.listWidget_2 = QtWidgets.QListWidget(self.groupBox_4)
        self.listWidget_2.setGeometry(QtCore.QRect(240, 50, 141, 311))
        self.listWidget_2.setStyleSheet("background: transparent;")
        self.listWidget_2.setObjectName("listWidget_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(240, 20, 161, 21))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_6.setGeometry(QtCore.QRect(10, 370, 141, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setText("")
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_7.setGeometry(QtCore.QRect(240, 370, 141, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_7.setFont(font)
        self.radioButton_7.setText("")
        self.radioButton_7.setObjectName("radioButton_7")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 410, 471, 51))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit.setGeometry(QtCore.QRect(140, 20, 71, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.renameimages = QtWidgets.QPushButton(self.groupBox_5)
        self.renameimages.setGeometry(QtCore.QRect(210, 20, 81, 21))
        self.renameimages.setStyleSheet("\n"
"background: transparent;")
        self.renameimages.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.renameimages.setIcon(icon1)
        self.renameimages.setIconSize(QtCore.QSize(30, 30))
        self.renameimages.setObjectName("renameimages")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_6.setGeometry(QtCore.QRect(570, 150, 311, 311))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 91, 41))
        self.pushButton.setStyleSheet("\n"
"background: transparent;")
        self.pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/virus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setIconSize(QtCore.QSize(25, 25))
        self.pushButton.setObjectName("pushButton")
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setGeometry(QtCore.QRect(40, 50, 241, 241))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.groupBox_24 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_24.setGeometry(QtCore.QRect(490, 10, 431, 131))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_24.setFont(font)
        self.groupBox_24.setObjectName("groupBox_24")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_24)
        self.comboBox.setGeometry(QtCore.QRect(10, 20, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_24)
        self.comboBox_2.setGeometry(QtCore.QRect(140, 20, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_24)
        self.lineEdit_6.setGeometry(QtCore.QRect(270, 20, 71, 41))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.dataagumen = QtWidgets.QPushButton(self.groupBox_24)
        self.dataagumen.setGeometry(QtCore.QRect(350, 20, 61, 51))
        self.dataagumen.setStyleSheet("\n"
"background: transparent;")
        self.dataagumen.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/duplicate (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dataagumen.setIcon(icon3)
        self.dataagumen.setIconSize(QtCore.QSize(40, 40))
        self.dataagumen.setObjectName("dataagumen")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 0, 951, 611))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 30, 921, 211))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 70, 121, 31))
        self.lineEdit_2.setStyleSheet("\n"
"background: transparent;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.convertexcel = QtWidgets.QPushButton(self.groupBox_8)
        self.convertexcel.setGeometry(QtCore.QRect(130, 60, 141, 51))
        self.convertexcel.setStyleSheet("\n"
"background: transparent;")
        self.convertexcel.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/xls.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.convertexcel.setIcon(icon4)
        self.convertexcel.setIconSize(QtCore.QSize(35, 35))
        self.convertexcel.setObjectName("convertexcel")
        self.tableView = QtWidgets.QTableView(self.groupBox_8)
        self.tableView.setGeometry(QtCore.QRect(330, 30, 421, 151))
        self.tableView.setObjectName("tableView")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_9.setGeometry(QtCore.QRect(20, 250, 921, 211))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.tableView_2 = QtWidgets.QTableView(self.groupBox_9)
        self.tableView_2.setGeometry(QtCore.QRect(480, 50, 421, 151))
        self.tableView_2.setObjectName("tableView_2")
        self.tableView_3 = QtWidgets.QTableView(self.groupBox_9)
        self.tableView_3.setGeometry(QtCore.QRect(20, 50, 421, 151))
        self.tableView_3.setObjectName("tableView_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_9)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_9)
        self.label_8.setGeometry(QtCore.QRect(480, 30, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_10.setGeometry(QtCore.QRect(20, 470, 921, 121))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 40, 121, 31))
        self.lineEdit_3.setStyleSheet("\n"
"background: transparent;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.ninfo = QtWidgets.QPushButton(self.groupBox_10)
        self.ninfo.setGeometry(QtCore.QRect(130, 30, 141, 51))
        self.ninfo.setStyleSheet("\n"
"background: transparent;")
        self.ninfo.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/jpg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ninfo.setIcon(icon5)
        self.ninfo.setIconSize(QtCore.QSize(35, 35))
        self.ninfo.setObjectName("ninfo")
        self.label_11 = QtWidgets.QLabel(self.groupBox_10)
        self.label_11.setGeometry(QtCore.QRect(270, 40, 631, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_14.setGeometry(QtCore.QRect(10, 10, 981, 621))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_14.setFont(font)
        self.groupBox_14.setObjectName("groupBox_14")
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_15.setGeometry(QtCore.QRect(20, 50, 311, 101))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_15.setFont(font)
        self.groupBox_15.setObjectName("groupBox_15")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_15)
        self.comboBox_3.setGeometry(QtCore.QRect(110, 30, 81, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setEditable(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_15)
        self.lineEdit_5.setGeometry(QtCore.QRect(20, 30, 61, 41))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.datasplit = QtWidgets.QPushButton(self.groupBox_15)
        self.datasplit.setGeometry(QtCore.QRect(210, 10, 71, 81))
        self.datasplit.setStyleSheet("\n"
"background: transparent;")
        self.datasplit.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/division.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.datasplit.setIcon(icon6)
        self.datasplit.setIconSize(QtCore.QSize(40, 40))
        self.datasplit.setObjectName("datasplit")
        self.groupBox_16 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_16.setGeometry(QtCore.QRect(370, 50, 201, 111))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_16.setFont(font)
        self.groupBox_16.setObjectName("groupBox_16")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_16)
        self.comboBox_4.setGeometry(QtCore.QRect(20, 40, 81, 31))
        self.comboBox_4.setObjectName("comboBox_4")
        self.kfoldshow = QtWidgets.QPushButton(self.groupBox_16)
        self.kfoldshow.setGeometry(QtCore.QRect(110, 20, 71, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.kfoldshow.setFont(font)
        self.kfoldshow.setStyleSheet("\n"
"background: transparent;")
        self.kfoldshow.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/click.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.kfoldshow.setIcon(icon7)
        self.kfoldshow.setIconSize(QtCore.QSize(40, 40))
        self.kfoldshow.setObjectName("kfoldshow")
        self.label_10 = QtWidgets.QLabel(self.groupBox_14)
        self.label_10.setGeometry(QtCore.QRect(600, 210, 211, 161))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_11.setGeometry(QtCore.QRect(20, 170, 561, 421))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.tableView_4 = QtWidgets.QTableView(self.groupBox_11)
        self.tableView_4.setGeometry(QtCore.QRect(20, 20, 281, 181))
        self.tableView_4.setObjectName("tableView_4")
        self.tableView_6 = QtWidgets.QTableView(self.groupBox_11)
        self.tableView_6.setGeometry(QtCore.QRect(250, 230, 281, 181))
        self.tableView_6.setObjectName("tableView_6")
        self.tableView_7 = QtWidgets.QTableView(self.groupBox_11)
        self.tableView_7.setGeometry(QtCore.QRect(30, 230, 191, 181))
        self.tableView_7.setObjectName("tableView_7")
        self.tableView_5 = QtWidgets.QTableView(self.groupBox_11)
        self.tableView_5.setGeometry(QtCore.QRect(340, 20, 191, 181))
        self.tableView_5.setObjectName("tableView_5")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_12.setGeometry(QtCore.QRect(600, 50, 361, 541))
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.label_22 = QtWidgets.QLabel(self.groupBox_12)
        self.label_22.setGeometry(QtCore.QRect(60, 120, 261, 261))
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_12)
        self.label_23.setGeometry(QtCore.QRect(60, 380, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_20 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_20.setGeometry(QtCore.QRect(10, 10, 981, 121))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_20.setFont(font)
        self.groupBox_20.setObjectName("groupBox_20")
        self.tlselect = QtWidgets.QPushButton(self.groupBox_20)
        self.tlselect.setGeometry(QtCore.QRect(890, 40, 91, 61))
        self.tlselect.setStyleSheet("\n"
"background: transparent;")
        self.tlselect.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/confirm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tlselect.setIcon(icon8)
        self.tlselect.setIconSize(QtCore.QSize(40, 40))
        self.tlselect.setObjectName("tlselect")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_20)
        self.radioButton.setGeometry(QtCore.QRect(40, 60, 95, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_20)
        self.radioButton_2.setGeometry(QtCore.QRect(180, 60, 95, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_20)
        self.radioButton_3.setGeometry(QtCore.QRect(350, 60, 131, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_20)
        self.radioButton_4.setGeometry(QtCore.QRect(520, 60, 131, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_20)
        self.radioButton_5.setGeometry(QtCore.QRect(690, 60, 95, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setObjectName("radioButton_5")
        self.groupBox_22 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_22.setGeometry(QtCore.QRect(620, 130, 371, 491))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_22.setFont(font)
        self.groupBox_22.setObjectName("groupBox_22")
        self.modeltest = QtWidgets.QPushButton(self.groupBox_22)
        self.modeltest.setGeometry(QtCore.QRect(20, 20, 91, 61))
        self.modeltest.setStyleSheet("\n"
"background: transparent;")
        self.modeltest.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/testing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.modeltest.setIcon(icon9)
        self.modeltest.setIconSize(QtCore.QSize(40, 40))
        self.modeltest.setObjectName("modeltest")
        self.label_17 = QtWidgets.QLabel(self.groupBox_22)
        self.label_17.setGeometry(QtCore.QRect(100, 30, 241, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_22)
        self.label_18.setGeometry(QtCore.QRect(70, 140, 241, 241))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_22)
        self.label_19.setGeometry(QtCore.QRect(110, 330, 181, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.groupBox_23 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_23.setGeometry(QtCore.QRect(10, 140, 591, 491))
        self.groupBox_23.setTitle("")
        self.groupBox_23.setObjectName("groupBox_23")
        self.label_15 = QtWidgets.QLabel(self.groupBox_23)
        self.label_15.setGeometry(QtCore.QRect(20, 230, 251, 251))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_23)
        self.label_16.setGeometry(QtCore.QRect(20, 40, 201, 151))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setText("")
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_16.setObjectName("label_16")
        self.label_20 = QtWidgets.QLabel(self.groupBox_23)
        self.label_20.setGeometry(QtCore.QRect(310, 230, 251, 251))
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_9 = QtWidgets.QLabel(self.groupBox_23)
        self.label_9.setGeometry(QtCore.QRect(20, 210, 241, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_21 = QtWidgets.QLabel(self.groupBox_23)
        self.label_21.setGeometry(QtCore.QRect(320, 210, 231, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_24 = QtWidgets.QLabel(self.groupBox_23)
        self.label_24.setGeometry(QtCore.QRect(210, 10, 361, 201))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableView_8 = QtWidgets.QTableView(self.tab_4)
        self.tableView_8.setGeometry(QtCore.QRect(100, 60, 851, 511))
        self.tableView_8.setObjectName("tableView_8")
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Upload Dataset"))
        self.groupBox_2.setTitle(_translate("Form", "Dataset Information"))
        self.groupBox_24.setTitle(_translate("Form", " Data Augmentation Methods"))
        self.comboBox.setItemText(0, _translate("Form", "Flipping"))
        self.comboBox.setItemText(1, _translate("Form", "Rotation"))
        self.comboBox.setItemText(2, _translate("Form", "Blur"))
        self.comboBox.setItemText(3, _translate("Form", "Make Border"))
        self.comboBox_2.setItemText(0, _translate("Form", "Covid"))
        self.comboBox_2.setItemText(1, _translate("Form", "Normal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Import Dataset- Augmentation"))
        self.groupBox_7.setTitle(_translate("Form", "One Hot Encoding"))
        self.groupBox_8.setTitle(_translate("Form", "convert to excel"))
        self.groupBox_9.setTitle(_translate("Form", " Label Encoding--One Hot Encoding"))
        self.label_7.setText(_translate("Form", "Label Encoding"))
        self.label_8.setText(_translate("Form", "One Hot Encoding"))
        self.groupBox_10.setTitle(_translate("Form", "nxn"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Data Processing"))
        self.groupBox_14.setTitle(_translate("Form", "Data Split"))
        self.groupBox_15.setTitle(_translate("Form", "Methods"))
        self.comboBox_3.setCurrentText(_translate("Form", "KFold"))
        self.comboBox_3.setItemText(0, _translate("Form", "KFold"))
        self.comboBox_3.setItemText(1, _translate("Form", "Holdout"))
        self.groupBox_16.setTitle(_translate("Form", "Show"))
        self.groupBox_11.setTitle(_translate("Form", "Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Data Split"))
        self.groupBox_20.setTitle(_translate("Form", "Transfer Learning Models"))
        self.radioButton.setText(_translate("Form", "VGG16"))
        self.radioButton_2.setText(_translate("Form", "RESNET50"))
        self.radioButton_3.setText(_translate("Form", "INCEPTION V3"))
        self.radioButton_4.setText(_translate("Form", "MOBİLENET V2"))
        self.radioButton_5.setText(_translate("Form", "XCEPTION"))
        self.groupBox_22.setTitle(_translate("Form", "Model Test"))
        self.label_18.setText(_translate("Form", "<html><head/><body><p><br/></p><p><br/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "Transfer Learning"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Page"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
